services:
  task-tracker-db:
    image: postgres:16.9-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  task-tracker-service:
    build: .
    image: task-tracker-service:latest
    environment:
      DATABASE_URL: postgresql://task-tracker-db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_SCHEMA: public
    depends_on:
      task-tracker-db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_data: